---
title: "CITS5507 Project2"
author: "Ame Liu(22910358)"
output:
  pdf_document: default
  html_document:
    df_print: paged
---



```{r}
library(ggplot2)
library(dplyr)
library(gridExtra)

```


```{r}
MPI <-read.csv ("/Users/liuyu/Desktop/MPI.csv")
MPI <- subset(MPI,select=c(Time,Sort,Types,Sequences,N))
QuickSort_1=subset(MPI ,N==10000 & Sort=="QuickSort")
QuickSort_1
ggplot(data = QuickSort_1, aes(x = Sequences, y = Time,  color = Types)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
 geom_hline(aes(yintercept=0), alpha = 0.65)+ggtitle("QuickSort_N=10000")

QuickSort_2=subset(MPI ,N==100000 & Sort=="QuickSort")
QuickSort_2
ggplot(data = QuickSort_2, aes(x = Sequences, y = Time,  color = Types)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
 geom_hline(aes(yintercept=0), alpha = 0.65)+ggtitle("QuickSort_N=100000")

EnumerationSort_1=subset(MPI ,N==10000 & Sort=="EnumerationSort")
EnumerationSort_1
ggplot(data = EnumerationSort_1, aes(x = Sequences, y = Time,  color = Types)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
 geom_hline(aes(yintercept=0), alpha = 0.65)+ggtitle("EnumerationSort_N=10000")
EnumerationSort_2=subset(MPI ,N==100000 & Sort=="EnumerationSort")
EnumerationSort_2
ggplot(data = EnumerationSort_2, aes(x = Sequences, y = Time,  color = Types)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
 geom_hline(aes(yintercept=0), alpha = 0.65)+ggtitle("EnumerationSort_N=100000")
MergeSort_1=subset(MPI ,N==10000 & Sort=="MergeSort")
MergeSort_1
ggplot(data = MergeSort_1, aes(x = Sequences, y = Time,  color = Types)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
 geom_hline(aes(yintercept=0), alpha = 0.65)+ggtitle("MergeSort_N=10000")
MergeSort_2=subset(MPI ,N==100000 & Sort=="MergeSort")
MergeSort_2
ggplot(data = MergeSort_2, aes(x = Sequences, y = Time,  color = Types)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
 geom_hline(aes(yintercept=0), alpha = 0.65)+ggtitle("MergeSort_N=100000")





```


