name: Display Report.md
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  display:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Display Report.md
      uses: rlespinasse/github-actions-readme@v1.0.0
      with:
        README_PATH: Optimizing_Classical_Sorting_by_OpenMP/OpenMP/Report.md
